# .github/workflows/express-backend.yml
name: Express Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # You can change this to match your project

      - name: Install dependencies
        run: npm install

      - name: Lint code (optional)
        run: npm run lint
        continue-on-error: true  # Avoid failing the workflow if linting is not critical

      - name: Build project
        run: npm run build

      # - name: Run unit tests
      #   run: npm test
